# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer
No console.log('Outside the loop'); will not run. This is because i will never be greater than 3. Because of this the loop will stop before  i = 3 so tht console.log('Outside the loop'); will not get the chance to exacute since its after i = 3


Revised***
No console.log('Outside the loop'); will not run. This is because the return function is runs before the loop ends. As a result the console.log('Outside the loop'); will not run because the function ends after return is called. 


# Teacher Feedback

Correct! Once i hits greater than 3, it causes the function to return, stopping any further code to not run, aka the second console.log. 

Score: 3/3